### ISSUE TITLE
compiler optimizations are turned off

### ISSUE THREAD

**Issue by stanleybak** [nasa/Kodiak#12]
`CMakeLists.txt` currently has the line:

`add_definitions(-Wall -frounding-math -pedantic -Wextra -Wno-parentheses -g -O0)`

This seems to compile all the code with `-O0`, which is going to make it run slow. In my single-experiment measurement, this runs about 10x slower than with `-O2`. Is there a correctness reason for this? Could we change this to `-O2`?

**Comment by cesaramh** [comment]
From Kodiak's point of view, there is nothing unsound about using compiler optimizations. However, the soundness of Kodiak depends on the soundness of filib++. They use -03, but recommend removing the flag if the library returns strange errors.
