### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [nasa/Kodiak#19]
I would like to point out that identifiers like “[`_KODIAK_`](https://github.com/nasa/Kodiak/blob/05e6bd185f77253eb2a7947f218765d0015df9e8/src/kodiak.hpp#L18 "Update candidate")” and “[`_PAVER_`](https://github.com/nasa/Kodiak/blob/db7cb1d30d37e97d2e1c7f426301410cac17cf9d/src/Paver.hpp#L1 "Another update candidate")” [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by mfeliu** [comment]
Thank you, I will fix the identifiers.

Did you inspect the code by hand or did you pass some static analysis tool?

Thanks again.

**Comment by elfring** [comment]
I am used to [the application](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?") of some source code search tools.
