### ISSUE TITLE
Docker to gain Windows support

### ISSUE THREAD

**Issue by joesho112358** [nasa/Kodiak#22]
In the README:
>Use of Windows is not supported, although it ought to be feasible, and the authors would welcome any report of successfully running the software on Windows or any other system.

On Windows 10 with Visual Studio 2019 installed- good enough?- I get:
```
> cmake ..
CMake Error at CMakeLists.txt:20 (project):
  Generator

    Visual Studio 15 2017

  could not find any instance of Visual Studio.



-- Configuring incomplete, errors occurred!
See also "C:/Kodiak/build/CMakeFiles/CMakeOutput.log".
```

And for completeness:
```
> cat C:/Kodiak/build/CMakeFiles/CMakeOutput.log
The system is: Windows - 10.0.18362 - AMD64
```

Would Docker help this effort for getting prerequisites set?

**Comment by cesaramh** [comment]
Use of Windows is not supported, although it ought to be feasible, and the authors would welcome any report of successfully running the software on Windows or any other system.
