### ISSUE TITLE
set_granularity error on large input files

### ISSUE THREAD

**Issue by stanleybak** [nasa/Kodiak#4]
When I have large input files with multiple minmax problems, I occasionally get an error (after some amount of time) similar to:

`Error:  'Kodiak (set_granularity): granularity 1.78881 must be in [0,1]'`

Here's an input file which produces this error, using the provided pre-built Ubuntu executable: [hyst_kodiak.kdk.txt](https://github.com/nasa/Kodiak/files/270957/hyst_kodiak.kdk.txt) (remove the .txt extension)

If I split the file into smaller parts though, each of the sub-parts works fine (no errors). In the provided input file, removing the first subproblem, or last sub-problem, will cause the error to go away. By subproblem, I mean:

```
reset;
set safe input = false;
set precision = -10;
set bp = true;
set resolution = 0.00001;

var x in [approx(-1.0650692030048177), approx(-0.8877081596699999)];
var y in [approx(-2.72286042061), approx(-2.5868220281409537)];

objfn (approx(1) - x * x) * y - x - (approx(-6.184313844456332) * x + approx(0.04666514295619591) * y - approx(5.06190535822799));
minmax;
```

**Comment by cesaramh** [comment]
Command-line interface is no longer supported in Kodiak.
