### ISSUE TITLE
incorrect result (and maximum's lb > ub) with Bernstein minmax

### ISSUE THREAD

**Issue by stanleybak** [nasa/Kodiak#9]
I perform a min-max operation and then call `lb_of_max()` and `ub_of_max()` on the answer. If I use `set_precision(-4)`, I get a reasonable answer:

```
bounds = min:[-0.0606, -0.0606] , max:[0.000336621, 0.000379688]
inclosure = [-0.0606, 0.00033662109]
outclosure = [-0.0606, 0.0003796875]
```

If I use `set_precision(-5)`, I get the unreasonable answer:

```
bounds = min:[-0.0606, -0.0606] , max:[0.00034314, 0.000339551]
inclosure = [-0.0606, 0.00034313965]
outclosure = [-0.0606, 0.00033955078]
```

notice that in the bounds now, the lower bound of the maximum, `0.00034314`, is greater than the upper bound `0.000339551`. Further, due to this the outclosure is incorrect and does not include the real maximum `0.00034386`: (see http://www.wolframalpha.com/input/?i=maximize+((1-x*x)*y-x)+-+(-7.44x+-+0.96y+%2B+9.016),++1.25%3C%3Dx%3C%3D1.55,+2.28%3C%3Dy%3C%3D+2.32 )

Here's the code:
```
#include <kodiak.hpp>

using namespace kodiak;
using std::cout;
using std::endl;

void run()
{
    Real x[] = {var("x"), var("y")};

    Real bias = val(approx(9.016));

    Real coeff_vec[] = {val(approx(-7.44)), val(approx(-0.96))}; //jac[dim_idx]

    Real nonlinear = ((1-x[0]*x[0])*x[1]-x[0]);
    Real linear = bias;

    for (int d = 0; d < 2; ++d)
        linear = linear + coeff_vec[d]*x[d];

    Real diff = nonlinear - linear;

    MinMaxSystem s1;

    // use bernstein polynomial enclosure?
    s1.setDefaultEnclosureMethodTrueForBernsteinAndFalseForIntervalArithmetic(true);

    s1.var("x", approx(1.25), approx(1.55));
    s1.var("y", approx(2.28), approx(2.32));

    s1.set_precision(-5);
    s1.minmax(diff);

    MinMax a = s1.answer();
    cout << "bounds = min:[" << a.lb_of_min() << ", " << a.ub_of_min() << "] , max:[" << a.lb_of_max() << ", " << a.ub_of_max() << "]" << endl;
    cout << "inclosure = " << a.inclosure() << endl;
    cout << "outclosure = " << a.outclosure() << endl;
}

int main(int, char *[]) {

    Kodiak::init();
    Kodiak::set_safe_input(false);

    try {
        run();
    } catch (Growl growl) {
        cout << growl.what() << endl;
    }
}
```

**Comment by stanleybak** [comment]
It seems this isn't limited to Bernstein minmax. If I do `s1.setDefaultEnclosureMethodTrueForBernsteinAndFalseForIntervalArithmetic(false);` and use `s1.set_precision(-6);` I also get an incorrect answer:

```
bounds = min:[-0.0606, -0.0606] , max:[0.00034386, 0.000338463]
inclosure = [-0.0606, 0.00034385965]
outclosure = [-0.0606, 0.00033846318]
```

**Comment by stanleybak** [comment]
If I run with `debug=2` I get a failing assertion on `isSound`:

```BranchAndBoundDF.hpp:151: void kodiak::BranchAndBoundDF<Expression, Answer, Environment>::branchAndBound(Answer&, const Expression&, const Environment&) [with Expression = kodiak::Certainties; Answer = kodiak::MinMax; Environment = kodiak::Environment]: Assertion `debug_ == 0 || isSound(answer, initialExpression_, initialBox_)' failed.```

**Comment by mfeliu** [comment]
It seems to be a problem with an optimization. I will have to look more deeply into it. In the meantime I have removed the optimization so that you can get sound results in this pull request  #10.

**Comment by cesaramh** [comment]
@stanleybak thanks for the report. We are looking into the issue, but in the meantime we commented the optimization that was causing the problem.

**Comment by mfeliu** [comment]
This pull request #11 should make it work with optimizations enabled again.

**Comment by stanleybak** [comment]
The result looks correct now, but I can no longer improve accuracy by using `set_precision` beyond a certain point. Using the same example code with `s1.set_precision(-9);` and `s1.setDefaultEnclosureMethodTrueForBernsteinAndFalseForIntervalArithmetic(false);`, I get the very coarse bounds: 

`bounds = min:[-0.110016, -0.0606] , max:[0.00034386, 0.108475]`

Whereas with the optimization disabled I get the much tighter bounds:

`bounds = min:[-0.0606, -0.0606] , max:[0.00034386, 0.00034386]`

**Comment by cesaramh** [comment]
@stanleybak Thanks again for the reports. Optimizations are enabled and precision is achieved in this example.
